### ISSUE TITLE
Forever log error

### ISSUE THREAD

**Issue by mttstt** [mttstt/Domoticasite#1]
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at Module.Mp.load (/home/pi/Domoticasite-node/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/Domoticasite-node/programs/server/npm/node_modules/wiring-pi/lib/exports.js:1:18)
error: Forever detected script exited with code: 1
error: Script restart attempt #998

**Comment by mttstt** [comment]
solved
