### ISSUE TITLE
Npm.depends

### ISSUE THREAD

**Issue by mttstt** [mttstt/Domoticasite#3]
pi@web ~/Domoticasite-node/bundle $ node main.js
System: undefined
/home/pi/Domoticasite-node/bundle/programs/server/node_modules/fibers/future.js:280
                                 throw(ex);
                                 ^

Error: Can't find npm module 'node-dht-sensor'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
    at Object.require (/home/pi/Domoticasite-node/bundle/programs/server/boot.js:203:17)
    at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
    at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:88:1)
    at Module.Mp.import (/home/pi/Domoticasite-node/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
    at server/server.js:137:30
    at /home/pi/Domoticasite-node/bundle/programs/server/boot.js:304:5
pi@web ~/Domoticasite-node/bundle $

**Comment by mttstt** [comment]
Solution: 
1. npm install --save wiring-pi
2. npm install --save git+https://github.com/HardwareProjects/node-dht-sensor.git
3. npm install
